# Generated by Django 2.2.1 on 2020-07-03 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Example1', '0002_auto_20200703_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='example1',
            name='curp',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='example1',
            name='edad',
            field=models.CharField(max_length=2),
        ),
    ]
